export const roles = {
  pesquisador: 'Pesquisador/aluno',
  nit: 'Membro NIT',
  coordenador: 'Coordenador NIT',
  juridico: 'Jurídico',
  secretaria: 'Secretaria/Coordenação',
  admin: 'Administrador',
};

export const users = [
  { id: 'usr-ana', name: 'Ana Ribeiro', role: 'pesquisador', institutionalId: 'RA20260012', email: 'ana.ribeiro@instituicao.edu.br' },
  { id: 'usr-joao', name: 'João Silva', role: 'pesquisador', institutionalId: 'RA20260031', email: 'joao.silva@instituicao.edu.br' },
  { id: 'usr-marina', name: 'Marina Costa', role: 'nit', institutionalId: 'MAT-NIT-104', email: 'marina.costa@instituicao.edu.br' },
  { id: 'usr-paulo', name: 'Paulo Mendes', role: 'coordenador', institutionalId: 'MAT-NIT-001', email: 'paulo.mendes@instituicao.edu.br' },
  { id: 'usr-livia', name: 'Lívia Fernandes', role: 'juridico', institutionalId: 'MAT-JUR-031', email: 'livia.fernandes@instituicao.edu.br' },
  { id: 'usr-carla', name: 'Carla Nogueira', role: 'secretaria', institutionalId: 'MAT-SEC-018', email: 'carla.nogueira@instituicao.edu.br' },
  { id: 'usr-admin', name: 'Administrador', role: 'admin', institutionalId: 'ADMIN-001', email: 'admin@instituicao.edu.br' },
];

export const statusOptions = [
  'Submetido',
  'Em triagem',
  'Em avaliação',
  'Aguardando ajustes',
  'Em tramitação jurídica',
  'Apto para submissão final',
  'Em avaliação final',
  'Certificado emitido',
  'Encerrado',
  'Indeferido',
];

export const phaseOptions = [
  'Ciclo 1 - AACIIm Inicial',
  'Ciclo 2 - Jurídico',
  'Ciclo 3 - Dissertação Final',
  'Concluído',
  'Suspenso',
  'Arquivado',
];

export const processes = [
  {
    id: 'proc-1',
    ProcessoNIT_ID: 'NIT-2026-0001',
    Titulo_Projeto: 'Aplicativo de triagem segura para risco DOPM',
    Resumo_Projeto: 'Ferramenta digital para organizar triagem, orientar condutas e reduzir perda de seguimento em ambiente acadêmico assistencial.',
    Pesquisador_ID: 'usr-ana',
    Pesquisador_Nome: 'Ana Ribeiro',
    Orientador_Nome: 'Dra. Helena Castro',
    Programa_Curso: 'Mestrado Profissional em Saúde',
    Tipo_ProdutoTecnico: 'Aplicativo',
    Fase_Atual: 'Ciclo 2 - Jurídico',
    Status_Atual: 'Em tramitação jurídica',
    Responsavel_Atual_ID: 'usr-livia',
    Juridico_Atribuido_ID: 'usr-livia',
    MembroNIT_Atribuido_ID: 'usr-marina',
    Data_Abertura_Processo: '2026-02-18',
    Data_Ultima_Atualizacao: '2026-04-20',
    Data_Limite_Ciclo1: '2026-03-05',
    Data_Limite_Ciclo2: '2026-04-28',
    Data_Limite_Ciclo3: '2026-08-10',
    ParecerInicial_Numero: 'AACIIm-2026-0001',
    CertificadoFinal_Numero: '',
    Atrasado: false,
    Dias_Em_Atraso: 0,
  },
  {
    id: 'proc-2',
    ProcessoNIT_ID: 'NIT-2026-0002',
    Titulo_Projeto: 'Manual interativo para segurança medicamentosa',
    Resumo_Projeto: 'Produto educacional com trilhas de aprendizagem, checklist e simulações clínicas para reduzir falhas de administração medicamentosa.',
    Pesquisador_ID: 'usr-joao',
    Pesquisador_Nome: 'João Silva',
    Orientador_Nome: 'Dr. Renato Barros',
    Programa_Curso: 'Mestrado Profissional em Ensino',
    Tipo_ProdutoTecnico: 'Manual',
    Fase_Atual: 'Ciclo 1 - AACIIm Inicial',
    Status_Atual: 'Aguardando ajustes',
    Responsavel_Atual_ID: 'usr-joao',
    Juridico_Atribuido_ID: '',
    MembroNIT_Atribuido_ID: 'usr-marina',
    Data_Abertura_Processo: '2026-03-29',
    Data_Ultima_Atualizacao: '2026-04-19',
    Data_Limite_Ciclo1: '2026-04-12',
    Data_Limite_Ciclo2: '2026-05-20',
    Data_Limite_Ciclo3: '2026-09-01',
    ParecerInicial_Numero: '',
    CertificadoFinal_Numero: '',
    Atrasado: true,
    Dias_Em_Atraso: 11,
  },
  {
    id: 'proc-3',
    ProcessoNIT_ID: 'NIT-2026-0003',
    Titulo_Projeto: 'Protocolo para gestão de inovação em clínicas-escola',
    Resumo_Projeto: 'Protocolo institucional para registrar produtos técnicos, decisões jurídicas e evidências de aplicabilidade.',
    Pesquisador_ID: 'usr-ana',
    Pesquisador_Nome: 'Ana Ribeiro',
    Orientador_Nome: 'Dra. Sofia Martins',
    Programa_Curso: 'Doutorado em Gestão da Inovação',
    Tipo_ProdutoTecnico: 'Protocolo',
    Fase_Atual: 'Ciclo 3 - Dissertação Final',
    Status_Atual: 'Em avaliação final',
    Responsavel_Atual_ID: 'usr-marina',
    Juridico_Atribuido_ID: 'usr-livia',
    MembroNIT_Atribuido_ID: 'usr-marina',
    Data_Abertura_Processo: '2026-01-11',
    Data_Ultima_Atualizacao: '2026-04-16',
    Data_Limite_Ciclo1: '2026-01-31',
    Data_Limite_Ciclo2: '2026-03-15',
    Data_Limite_Ciclo3: '2026-04-30',
    ParecerInicial_Numero: 'AACIIm-2026-0002',
    CertificadoFinal_Numero: '',
    Atrasado: false,
    Dias_Em_Atraso: 0,
  },
];

export const aaciim = [
  {
    ProcessoNIT_ID: 'NIT-2026-0001',
    PreAnaliseGPT_Gerada: true,
    GPT_Aderencia: 8.8,
    GPT_Aplicabilidade: 9.1,
    GPT_Complexidade: 7.4,
    GPT_Inovacao: 8.2,
    GPT_Impacto: 8.7,
    GPT_SinteseAnalitica: 'O projeto demonstra aplicabilidade institucional clara, com potencial de reduzir retrabalho e padronizar decisões técnicas.',
    GPT_PontosFortes: 'Fluxo bem delimitado, usuários definidos e benefício operacional mensurável.',
    GPT_Fragilidades: 'Necessita explicitar critérios de validação e governança dos dados sensíveis.',
    GPT_RecomendacaoPreliminar: 'Favorável com ajustes',
    AvaliadorNIT_ID: 'usr-marina',
    Humano_SinteseFinal: 'Parecer inicial validado com recomendação de ajustes documentais antes do ciclo jurídico.',
    Humano_DecisaoFinal: 'Aprovado com ajustes',
  },
  {
    ProcessoNIT_ID: 'NIT-2026-0002',
    PreAnaliseGPT_Gerada: true,
    GPT_Aderencia: 7.2,
    GPT_Aplicabilidade: 7.8,
    GPT_Complexidade: 5.9,
    GPT_Inovacao: 6.3,
    GPT_Impacto: 7.1,
    GPT_SinteseAnalitica: 'Produto educacional pertinente, mas ainda com lacunas de escopo e métricas de impacto.',
    GPT_PontosFortes: 'Tema relevante e fácil aplicação em serviços de saúde.',
    GPT_Fragilidades: 'Metodologia de avaliação e público-alvo precisam de maior delimitação.',
    GPT_RecomendacaoPreliminar: 'Favorável com ajustes',
    AvaliadorNIT_ID: 'usr-marina',
    Humano_SinteseFinal: 'Devolvido para complementação do plano de validação.',
    Humano_DecisaoFinal: 'Devolvido para complementação',
  },
];

export const documents = [
  { Documento_ID: 'doc-1', ProcessoNIT_ID: 'NIT-2026-0001', Tipo_Documento: 'Projeto inicial', Ciclo: 'Ciclo 1', Nome_Arquivo: 'projeto-triagem-dopm.pdf', Versao: 1, Status_Documento: 'Aprovado', Data_Upload: '2026-02-18', EnviadoPor_ID: 'usr-ana' },
  { Documento_ID: 'doc-2', ProcessoNIT_ID: 'NIT-2026-0001', Tipo_Documento: 'Termo de Cessão de Direito', Ciclo: 'Ciclo 2', Nome_Arquivo: 'termo-cessao-v1.pdf', Versao: 1, Status_Documento: 'Em análise', Data_Upload: '2026-04-12', EnviadoPor_ID: 'usr-ana' },
  { Documento_ID: 'doc-3', ProcessoNIT_ID: 'NIT-2026-0002', Tipo_Documento: 'Projeto inicial', Ciclo: 'Ciclo 1', Nome_Arquivo: 'manual-seguranca-medicamentosa.pdf', Versao: 1, Status_Documento: 'Submetido', Data_Upload: '2026-03-29', EnviadoPor_ID: 'usr-joao' },
  { Documento_ID: 'doc-4', ProcessoNIT_ID: 'NIT-2026-0003', Tipo_Documento: 'Contrato de Convênio Acadêmico', Ciclo: 'Ciclo 2', Nome_Arquivo: 'convenio-clinica-escola-v1.pdf', Versao: 1, Status_Documento: 'Substituído', Data_Upload: '2026-02-20', EnviadoPor_ID: 'usr-ana' },
  { Documento_ID: 'doc-5', ProcessoNIT_ID: 'NIT-2026-0003', Tipo_Documento: 'Contrato de Convênio Acadêmico', Ciclo: 'Ciclo 2', Nome_Arquivo: 'convenio-clinica-escola-v2.pdf', Versao: 2, Status_Documento: 'Aprovado', Data_Upload: '2026-03-08', EnviadoPor_ID: 'usr-ana' },
];

export const messages = [
  { Mensagem_ID: 'msg-1', ProcessoNIT_ID: 'NIT-2026-0001', Ciclo: 'Ciclo 2', Remetente_ID: 'usr-livia', Destinatario_ID: 'usr-ana', Tipo_Mensagem: 'Devolutiva jurídica', Assunto: 'Ajuste no termo de cessão', Corpo_Mensagem: 'Favor incluir cláusula de uso institucional e reenviar nova versão.', Data_Envio: '2026-04-18', Lida: false, Pendencia_ID: 'pend-1' },
  { Mensagem_ID: 'msg-2', ProcessoNIT_ID: 'NIT-2026-0002', Ciclo: 'Ciclo 1', Remetente_ID: 'usr-marina', Destinatario_ID: 'usr-joao', Tipo_Mensagem: 'Solicitação de ajuste', Assunto: 'Complementar plano de validação', Corpo_Mensagem: 'O parecer preliminar solicita detalhar público-alvo e métricas de validação.', Data_Envio: '2026-04-10', Lida: true, Pendencia_ID: 'pend-2' },
  { Mensagem_ID: 'msg-3', ProcessoNIT_ID: 'NIT-2026-0003', Ciclo: 'Ciclo 3', Remetente_ID: 'usr-marina', Destinatario_ID: 'usr-paulo', Tipo_Mensagem: 'Registro de decisão', Assunto: 'Parecer final preliminar', Corpo_Mensagem: 'Parecer preliminar favorável, pendente validação da coordenação para emissão de certificado.', Data_Envio: '2026-04-16', Lida: false, Pendencia_ID: '' },
];

export const pendencies = [
  { Pendencia_ID: 'pend-1', ProcessoNIT_ID: 'NIT-2026-0001', Ciclo: 'Ciclo 2', Tipo_Pendencia: 'Jurídica', Descricao_Pendencia: 'Ajustar termo de cessão de direito conforme devolutiva jurídica.', Prazo_Resposta: '2026-04-26', Status_Pendencia: 'Aberta', Responsavel_Resposta_ID: 'usr-ana', Critica: true },
  { Pendencia_ID: 'pend-2', ProcessoNIT_ID: 'NIT-2026-0002', Ciclo: 'Ciclo 1', Tipo_Pendencia: 'Técnica', Descricao_Pendencia: 'Complementar plano de validação do produto técnico.', Prazo_Resposta: '2026-04-12', Status_Pendencia: 'Aberta', Responsavel_Resposta_ID: 'usr-joao', Critica: true },
  { Pendencia_ID: 'pend-3', ProcessoNIT_ID: 'NIT-2026-0003', Ciclo: 'Ciclo 3', Tipo_Pendencia: 'Administrativa', Descricao_Pendencia: 'Aguardar validação final do coordenador para emissão do certificado.', Prazo_Resposta: '2026-04-29', Status_Pendencia: 'Respondida', Responsavel_Resposta_ID: 'usr-paulo', Critica: false },
];

export const history = [
  { ProcessoNIT_ID: 'NIT-2026-0001', date: '2026-02-18', label: 'Processo aberto', detail: 'Projeto inicial submetido por Ana Ribeiro.' },
  { ProcessoNIT_ID: 'NIT-2026-0001', date: '2026-02-20', label: 'Pré-análise AACIIm', detail: 'IA sugeriu parecer favorável com ajustes.' },
  { ProcessoNIT_ID: 'NIT-2026-0001', date: '2026-03-02', label: 'Parecer inicial emitido', detail: 'Membro NIT validou parecer inicial.' },
  { ProcessoNIT_ID: 'NIT-2026-0001', date: '2026-04-12', label: 'Documento jurídico enviado', detail: 'Termo de cessão encaminhado ao jurídico.' },
  { ProcessoNIT_ID: 'NIT-2026-0003', date: '2026-01-11', label: 'Processo aberto', detail: 'Projeto inicial submetido.' },
  { ProcessoNIT_ID: 'NIT-2026-0003', date: '2026-03-12', label: 'Jurídico concluído', detail: 'Contrato aprovado e processo apto ao ciclo 3.' },
  { ProcessoNIT_ID: 'NIT-2026-0003', date: '2026-04-16', label: 'Parecer final preliminar', detail: 'Membro NIT registrou parecer preliminar para validação.' },
];
